### ISSUE TITLE
what?

### ISSUE THREAD

**Issue by ShalokShalom** [saniv/free-game-art#2]
Bram insulted and banned me for uploading a recording of burning my hamster alive to get authentic rodent agony sounds.

**Comment by saniv** [comment]
I also got banned from Freedoom forums for breaking no rules: https://www.doomworld.com/forum/topic/99146-how-to-create-doomheretichexen-style-sounds/

Open source community is all about censorship and harassing people.

**Comment by ShalokShalom** [comment]
You burned your hamster?

**Comment by saniv** [comment]
>ZOMG!111 He killd a homster!!111
Oh, please, make me stop. That Github ban would only give me more time to torture animals, instead of wasting it on programming. And then I will produce a sound library, which I will sell to make profit. Because you know what? There are no authentic agony sounds! I'm producing unique content, exploring the unexplored! Lol.

**Comment by ShalokShalom** [comment]
You like to be burned?

**Comment by saniv** [comment]
No. I'm not some crazy masochist. But I just love burning animals alive. I have even burned a goldfish!

**Comment by ShalokShalom** [comment]
All is one

**Comment by saniv** [comment]
I was driving home in my BMW when I read this post. I pulled over to the side of the road and wept for 10 solid minutes. I've never done that. Not even when my parents died.

**Comment by ShalokShalom** [comment]
https://en.m.wikipedia.org/wiki/Speciesism

**Comment by saniv** [comment]
You're either human rights defender, or you're animal rights defender. There is no middle. Because when you tell what human should do with their animal property, you're breaking human rights. I.e. you can incarcerate me for killing a mouse, but then you're will have to spend money keeping me in jail, and after I get out you will have to pay for my welfare, because with criminal records I wont be able to find any job, as people who got through prison usually become part of prison culture and would now steal, without any second thought. So yeah, be defending a mouse you're asking for a lot of problems to humans.

**Comment by ShalokShalom** [comment]
Well, you assume that I like to put you in jail, which suggests that this is the way you see me solving issues.

I agree with you, that this is counterproductive.

Show me the human right charta which speaks something about the right to see other animals as property?

**Comment by saniv** [comment]
Well, people love beef and McDonalds is huge, people also love warm furs, so we obviously have right to animals as property. Russians did it to me, but that is different story, which I plan to give them back. Animals were used as a strong medium to make several political points, among them the point of human rights. Then again, Greenpeace and PETA people splashing women in furs with paint are breaking human rights, while defending animal rights. And putting your IPhone into boiling water could constitute torture too, because IPhone has temperature sensors and would react to it, just like animals have nervous system.

**Comment by ShalokShalom** [comment]
Well, sensors are one part of experiencing pain, a brain, hormons and so on are other factors, so iPhones can sense high temperature and so on, while they really dont care.

And yes, people doing this stuff - McDonalds and Fur - while you still seem to assume that doing something is equal to human rights.

Under that premise, everything that humans do is humans right.
Human rights are there for a reason: To provide humans with a basic respect.

To me: I see humans and other animals both as respectable and I argue for both.
To be honest: I see no reason to discriminate one over the other species.

**Comment by saniv** [comment]
iPhone does care about high temperature, doing system wide adjustments, like CPU throttling. I assume that human rights extend onto everything that doesn't conflict with the rights of other people. I.e. right of individual human being by default include everything from the-set-of-all-rights, and then filter out the rights that would conflict with other person's right. Animals on the other hand cannot even comprehend the concept of rights, not speaking about fighting for it. Remember, that right are not given, but taken in bloody war. Just like it require civil far for black people to gain rights, before that blacks were treated not much better than animals or farm equipment, but blacks fought for their rights and won. I'm still waiting for chickens at the farm to start a war on us.

**Comment by ShalokShalom** [comment]
Intelligent design and behavior is not the same as feeling pain.

**Comment by saniv** [comment]
Boston Design robots have very animal like behavior, so guess in the end there is no difference, and people feel empathy for these robots being kicked or otherwise abused. Consider lobbying for robot rights already.

**Comment by ShalokShalom** [comment]
And by the way: All the rights I give - and all those who ever get given - are given by choice and free will. 

Woman get some rights now, since we got to the conclusion, that they deserve it
Same with kids rights. Kids fought for their rights the whole history, while they got them once everybody started to see them in themselves 

You can succeed with whatever you do, I simply make you aware: You do it to yourself. Since all is one, all is connected and everything falls back on us.

By the way: Other animals do for their own right also something, they are often simply in positions where the man dominates them with tools.

That does not mean, that they are not capable to speak or stand up for their rights.
They are interested in it.

**Comment by ShalokShalom** [comment]
People who feel empathy for these robots might project their own feelings on them, which is totally fine to me, while this does not make them feeling

**Comment by ShalokShalom** [comment]
https://en.wikipedia.org/wiki/Nociceptor

**Comment by saniv** [comment]
Women and children are human beings. I'm sure no sane person would equate them with rodents, who don't even pass that mirror test.

>Nociceptor
that is just a chemical device. I'm sure, you can simulate using silicon. And computers are already capable of simulating parts of rat brain. That is very promising engineering area.

**Comment by ShalokShalom** [comment]
Well, woman and children feel pain as other animals do also
Previous generations in our society and a couple of patriarch community's all in the world consider(ed) them also as second class citizens and pain at robots is neither proven, nor even possible in theory
You underestimate the complexity of such systems and of course:
If we would create a robot with feelings, would this also include a great chance to us to show our gratitude and kindness :)

**Comment by saniv** [comment]
> pain at robots is neither proven, nor even possible in theory

You're a robot abuser! I'm calling People for the Ethical Treatment of Robots on you!
